//
//Nudm_SDM
//
//Nudm Subscriber Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
//
//The version of the OpenAPI document: 2.1.7
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.10.0
// source: lte/protos/models/sms_management_subscription_data.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SmsManagementSubscriptionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupportedFeatures   string `protobuf:"bytes,46698251,opt,name=supportedFeatures,proto3" json:"supportedFeatures,omitempty"`
	MtSmsSubscribed     bool   `protobuf:"varint,115610670,opt,name=mtSmsSubscribed,proto3" json:"mtSmsSubscribed,omitempty"`
	MtSmsBarringAll     bool   `protobuf:"varint,337983057,opt,name=mtSmsBarringAll,proto3" json:"mtSmsBarringAll,omitempty"`
	MtSmsBarringRoaming bool   `protobuf:"varint,251720536,opt,name=mtSmsBarringRoaming,proto3" json:"mtSmsBarringRoaming,omitempty"`
	MoSmsSubscribed     bool   `protobuf:"varint,40950768,opt,name=moSmsSubscribed,proto3" json:"moSmsSubscribed,omitempty"`
	MoSmsBarringAll     bool   `protobuf:"varint,42326424,opt,name=moSmsBarringAll,proto3" json:"moSmsBarringAll,omitempty"`
	MoSmsBarringRoaming bool   `protobuf:"varint,438673933,opt,name=moSmsBarringRoaming,proto3" json:"moSmsBarringRoaming,omitempty"`
}

func (x *SmsManagementSubscriptionData) Reset() {
	*x = SmsManagementSubscriptionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_models_sms_management_subscription_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsManagementSubscriptionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsManagementSubscriptionData) ProtoMessage() {}

func (x *SmsManagementSubscriptionData) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_models_sms_management_subscription_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsManagementSubscriptionData.ProtoReflect.Descriptor instead.
func (*SmsManagementSubscriptionData) Descriptor() ([]byte, []int) {
	return file_lte_protos_models_sms_management_subscription_data_proto_rawDescGZIP(), []int{0}
}

func (x *SmsManagementSubscriptionData) GetSupportedFeatures() string {
	if x != nil {
		return x.SupportedFeatures
	}
	return ""
}

func (x *SmsManagementSubscriptionData) GetMtSmsSubscribed() bool {
	if x != nil {
		return x.MtSmsSubscribed
	}
	return false
}

func (x *SmsManagementSubscriptionData) GetMtSmsBarringAll() bool {
	if x != nil {
		return x.MtSmsBarringAll
	}
	return false
}

func (x *SmsManagementSubscriptionData) GetMtSmsBarringRoaming() bool {
	if x != nil {
		return x.MtSmsBarringRoaming
	}
	return false
}

func (x *SmsManagementSubscriptionData) GetMoSmsSubscribed() bool {
	if x != nil {
		return x.MoSmsSubscribed
	}
	return false
}

func (x *SmsManagementSubscriptionData) GetMoSmsBarringAll() bool {
	if x != nil {
		return x.MoSmsBarringAll
	}
	return false
}

func (x *SmsManagementSubscriptionData) GetMoSmsBarringRoaming() bool {
	if x != nil {
		return x.MoSmsBarringRoaming
	}
	return false
}

var File_lte_protos_models_sms_management_subscription_data_proto protoreflect.FileDescriptor

var file_lte_protos_models_sms_management_subscription_data_proto_rawDesc = []byte{
	0x0a, 0x38, 0x6c, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2f, 0x73, 0x6d, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x61, 0x67, 0x6d,
	0x61, 0x2e, 0x6c, 0x74, 0x65, 0x22, 0xf0, 0x02, 0x0a, 0x1d, 0x53, 0x6d, 0x73, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x11, 0x73, 0x75, 0x70, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x8b, 0x9e, 0xa2,
	0x16, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x0f, 0x6d, 0x74, 0x53, 0x6d,
	0x73, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x18, 0xae, 0xa8, 0x90, 0x37,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x6d, 0x74, 0x53, 0x6d, 0x73, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x0f, 0x6d, 0x74, 0x53, 0x6d, 0x73, 0x42, 0x61,
	0x72, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x6c, 0x6c, 0x18, 0xd1, 0xec, 0x94, 0xa1, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0f, 0x6d, 0x74, 0x53, 0x6d, 0x73, 0x42, 0x61, 0x72, 0x72, 0x69, 0x6e, 0x67,
	0x41, 0x6c, 0x6c, 0x12, 0x33, 0x0a, 0x13, 0x6d, 0x74, 0x53, 0x6d, 0x73, 0x42, 0x61, 0x72, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x6f, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0xd8, 0xe6, 0x83, 0x78, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x13, 0x6d, 0x74, 0x53, 0x6d, 0x73, 0x42, 0x61, 0x72, 0x72, 0x69, 0x6e,
	0x67, 0x52, 0x6f, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x2b, 0x0a, 0x0f, 0x6d, 0x6f, 0x53, 0x6d,
	0x73, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x18, 0xf0, 0xb7, 0xc3, 0x13,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x6d, 0x6f, 0x53, 0x6d, 0x73, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x64, 0x12, 0x2b, 0x0a, 0x0f, 0x6d, 0x6f, 0x53, 0x6d, 0x73, 0x42, 0x61,
	0x72, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x6c, 0x6c, 0x18, 0x98, 0xb3, 0x97, 0x14, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0f, 0x6d, 0x6f, 0x53, 0x6d, 0x73, 0x42, 0x61, 0x72, 0x72, 0x69, 0x6e, 0x67, 0x41,
	0x6c, 0x6c, 0x12, 0x34, 0x0a, 0x13, 0x6d, 0x6f, 0x53, 0x6d, 0x73, 0x42, 0x61, 0x72, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x6f, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x8d, 0xc4, 0x96, 0xd1, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x13, 0x6d, 0x6f, 0x53, 0x6d, 0x73, 0x42, 0x61, 0x72, 0x72, 0x69, 0x6e,
	0x67, 0x52, 0x6f, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x42, 0x22, 0x5a, 0x20, 0x6d, 0x61, 0x67, 0x6d,
	0x61, 0x2f, 0x6c, 0x74, 0x65, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x67, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lte_protos_models_sms_management_subscription_data_proto_rawDescOnce sync.Once
	file_lte_protos_models_sms_management_subscription_data_proto_rawDescData = file_lte_protos_models_sms_management_subscription_data_proto_rawDesc
)

func file_lte_protos_models_sms_management_subscription_data_proto_rawDescGZIP() []byte {
	file_lte_protos_models_sms_management_subscription_data_proto_rawDescOnce.Do(func() {
		file_lte_protos_models_sms_management_subscription_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_lte_protos_models_sms_management_subscription_data_proto_rawDescData)
	})
	return file_lte_protos_models_sms_management_subscription_data_proto_rawDescData
}

var file_lte_protos_models_sms_management_subscription_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lte_protos_models_sms_management_subscription_data_proto_goTypes = []interface{}{
	(*SmsManagementSubscriptionData)(nil), // 0: magma.lte.SmsManagementSubscriptionData
}
var file_lte_protos_models_sms_management_subscription_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lte_protos_models_sms_management_subscription_data_proto_init() }
func file_lte_protos_models_sms_management_subscription_data_proto_init() {
	if File_lte_protos_models_sms_management_subscription_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lte_protos_models_sms_management_subscription_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsManagementSubscriptionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lte_protos_models_sms_management_subscription_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lte_protos_models_sms_management_subscription_data_proto_goTypes,
		DependencyIndexes: file_lte_protos_models_sms_management_subscription_data_proto_depIdxs,
		MessageInfos:      file_lte_protos_models_sms_management_subscription_data_proto_msgTypes,
	}.Build()
	File_lte_protos_models_sms_management_subscription_data_proto = out.File
	file_lte_protos_models_sms_management_subscription_data_proto_rawDesc = nil
	file_lte_protos_models_sms_management_subscription_data_proto_goTypes = nil
	file_lte_protos_models_sms_management_subscription_data_proto_depIdxs = nil
}
